# Generated by Django 4.2.14 on 2025-06-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="indexed",
            field=models.BooleanField(default=False),
        ),
    ]
